name: commec-dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.10
  # Runtime Python dependencies
  - biopython
  - numpy
  - pandas
  - pyyaml
  - pycountry
  # Runtime GUI (web kiosk) server deps
  - flask
  - openpyxl
  - xlrd
  - werkzeug
  - psutil
  - mkcert
  # Runtime non-Python dependencies
  - blast>=2.17
  - hmmer
  - infernal
  - tar
  - zstd
  # Development dependencies
  - pip
  - pytest
  - xlwt
  - ruff>=0.15.10,<0.16.0
  - pip:
      - -e .
